// Mock data for the prototype — adds snippets, shortName, fills out Northwind
const TENANTS = {
  meridian: {
    id: 'meridian',
    name: 'Meridian Health',
    short: 'Patient knowledge portal',
    mark: 'M',
    primary: '#0d6e6e',
    primaryFg: '#ffffff',
    accent: '#d97757',
    bg: '#fcfcfb',
    domain: 'help.meridianhealth.example',
    welcome: 'Hi, I\'m the Meridian assistant.',
    welcomeSub: 'Ask anything about your care plan, medications, or appointments. Every answer cites the source from your records.',
    prompts: [
      { cat: 'Care plan', text: 'What does my new diabetes management plan involve?' },
      { cat: 'Medications', text: 'Are there interactions between metformin and my other meds?' },
      { cat: 'Appointments', text: 'When is my next cardiology follow-up?' },
      { cat: 'Symptoms', text: 'What side effects should I watch for after surgery?' },
    ],
    docs: [
      { id: 'd1', name: 'Patient Handbook 2026.pdf', shortName: 'Patient Handbook', type: 'pdf', size: '4.2 MB', pages: 84, status: 'ready', uploaded: '2026-04-12', uploadedBy: 'Dana Reyes', folder: 'General', tags: ['handbook','onboarding'], queries: 412, snippets: ['Patients should review their care plan with the assigned nurse navigator within 7 days of admission.'] },
      { id: 'd2', name: 'Diabetes Care Protocol v3.docx', shortName: 'Diabetes Care Protocol', type: 'docx', size: '1.8 MB', pages: 22, status: 'ready', uploaded: '2026-04-18', uploadedBy: 'Dr. K. Singh', folder: 'Protocols', tags: ['protocol','endocrine'], queries: 287, snippets: ['Initial therapy is metformin 500 mg twice daily, titrated weekly to a target of 1000 mg twice daily as tolerated.','HbA1c is rechecked at 12 weeks; targets are individualized but generally <7.0% for adults under 65.'] },
      { id: 'd3', name: 'Medication Interaction Reference.pdf', shortName: 'Medication Interactions', type: 'pdf', size: '12.4 MB', pages: 246, status: 'ready', uploaded: '2026-04-20', uploadedBy: 'Pharmacy Ops', folder: 'Pharmacy', tags: ['meds','reference'], queries: 198, snippets: ['Metformin has no clinically significant interaction with lisinopril or atorvastatin at standard doses.'] },
      { id: 'd4', name: 'Post-Op Recovery Guide.pdf', shortName: 'Post-Op Recovery', type: 'pdf', size: '2.6 MB', pages: 38, status: 'indexing', uploaded: '2026-05-04', uploadedBy: 'Dana Reyes', folder: 'Surgery', tags: ['recovery'], queries: 0, progress: 64 },
      { id: 'd5', name: 'Insurance & Billing FAQ.md', shortName: 'Insurance & Billing FAQ', type: 'md', size: '128 KB', pages: 12, status: 'ready', uploaded: '2026-03-29', uploadedBy: 'Billing Team', folder: 'Admin', tags: ['billing'], queries: 156, snippets: ['Most in-network specialist visits are covered after a $35 copay; out-of-pocket maximums apply per plan year.'] },
      { id: 'd6', name: 'Cardiology Patient Pathway.docx', shortName: 'Cardiology Pathway', type: 'docx', size: '920 KB', pages: 14, status: 'ready', uploaded: '2026-04-02', uploadedBy: 'Dr. L. Chen', folder: 'Protocols', tags: ['cardiology','pathway'], queries: 134, snippets: ['Follow-up after a cardiac event is scheduled at 2 weeks, then 6 weeks, then quarterly for the first year.'] },
      { id: 'd7', name: 'Visitor Policy 2026.pdf', shortName: 'Visitor Policy', type: 'pdf', size: '340 KB', pages: 4, status: 'ready', uploaded: '2026-01-15', uploadedBy: 'Admin', folder: 'General', tags: ['policy'], queries: 21 },
      { id: 'd8', name: 'Wellness Programs Overview.txt', shortName: 'Wellness Programs', type: 'txt', size: '46 KB', pages: 6, status: 'ready', uploaded: '2026-02-22', uploadedBy: 'Wellness Team', folder: 'General', tags: ['wellness'], queries: 67 },
      { id: 'd9', name: 'Pediatric Vaccine Schedule.pdf', shortName: 'Pediatric Vaccines', type: 'pdf', size: '1.1 MB', pages: 18, status: 'queued', uploaded: '2026-05-06', uploadedBy: 'Dr. M. Patel', folder: 'Pediatrics', tags: ['vaccines','pediatric'], queries: 0, progress: 0 },
      { id: 'd10', name: 'Lab Results Glossary.docx', shortName: 'Lab Glossary', type: 'docx', size: '760 KB', pages: 28, status: 'ready', uploaded: '2026-03-11', uploadedBy: 'Lab Ops', folder: 'General', tags: ['labs'], queries: 89 },
    ],
    users: [
      { id: 'u1', name: 'Dana Reyes', email: 'dana.reyes@meridianhealth.example', role: 'Admin', last: '12 min ago', status: 'active' },
      { id: 'u2', name: 'Dr. Karim Singh', email: 'k.singh@meridianhealth.example', role: 'Editor', last: '2 hours ago', status: 'active' },
      { id: 'u3', name: 'Jordan Lee', email: 'jordan.lee@example.com', role: 'End User', last: '34 min ago', status: 'active' },
      { id: 'u4', name: 'Priya Shah', email: 'priya.shah@example.com', role: 'End User', last: '1 day ago', status: 'active' },
      { id: 'u5', name: 'Marcus Webb', email: 'marcus.webb@example.com', role: 'End User', last: '3 days ago', status: 'active' },
      { id: 'u6', name: 'Yuki Tanaka', email: 'yuki.t@example.com', role: 'End User', last: '5 hours ago', status: 'active' },
      { id: 'u7', name: 'Aisha Okafor', email: 'aisha.o@example.com', role: 'End User', last: 'Pending invite', status: 'pending' },
      { id: 'u8', name: 'Tom Bergman', email: 'tom.b@example.com', role: 'End User', last: '14 days ago', status: 'inactive' },
    ],
    audit: [
      { who: 'Dana Reyes', what: 'uploaded', target: 'Pediatric Vaccine Schedule.pdf', when: '12 min ago' },
      { who: 'Dr. K. Singh', what: 'updated branding', target: 'Primary color', when: '2 hours ago' },
      { who: 'Dana Reyes', what: 'invited', target: 'aisha.o@example.com', when: '4 hours ago' },
      { who: 'System', what: 'auto-deleted', target: 'Old Handbook 2024.pdf', when: '8 hours ago' },
      { who: 'Dr. K. Singh', what: 'edited welcome', target: 'Chat home screen', when: '1 day ago' },
      { who: 'Dana Reyes', what: 'set role', target: 'Dr. K. Singh → Editor', when: '2 days ago' },
      { who: 'Pharmacy Ops', what: 'uploaded', target: 'Medication Interaction Reference.pdf', when: '16 days ago' },
    ],
    topQueries: [
      { q: 'side effects of metformin', count: 142 },
      { q: 'when should I take my blood pressure medication', count: 98 },
      { q: 'preparing for colonoscopy', count: 87 },
      { q: 'visiting hours on weekends', count: 76 },
      { q: 'how to read my lab results', count: 64 },
      { q: 'insurance coverage for physical therapy', count: 51 },
    ],
    plan: 'Growth',
    usage: { docs: 84, docsLimit: 250, queries: 12840, queriesLimit: 25000, users: 312, usersLimit: 500, storage: 2.4, storageLimit: 10 },
  },
};

// Northwind variant inherits docs from Meridian for prototype simplicity, but with its own brand
TENANTS.northwind = {
  ...TENANTS.meridian,
  id: 'northwind',
  name: 'Northwind Legal',
  short: 'Case research assistant',
  mark: 'N',
  primary: '#1e3a8a',
  primaryFg: '#ffffff',
  accent: '#a16207',
  bg: '#fbfbfa',
  domain: 'research.northwind-legal.example',
  welcome: 'Northwind research assistant.',
  welcomeSub: 'Search case law, contracts, and internal memos. Every claim is grounded with paragraph-level citations.',
  prompts: [
    { cat: 'Case law', text: 'What\'s the standard for force majeure in NY state contracts?' },
    { cat: 'Contracts', text: 'Summarize the indemnification clauses across our 2025 MSAs' },
    { cat: 'Memos', text: 'What did we recommend on the Acme matter?' },
    { cat: 'Process', text: 'What\'s our intake checklist for new clients?' },
  ],
  plan: 'Enterprise',
  usage: { docs: 1240, docsLimit: 5000, queries: 48200, queriesLimit: 100000, users: 84, usersLimit: 200, storage: 18.7, storageLimit: 100 },
};

window.TENANTS = TENANTS;